version: '3'
services:
  shell:
    build: .
    image: eemeter_shell
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    volumes:
      - .:/app
      - /app/tests/__pycache__/

  test:
    image: eemeter_shell
    entrypoint: py.test -n0
    volumes:
      - .:/app
      - /app/tests/__pycache__/
    depends_on:
      - shell

  jupyter:
    image: eemeter_shell
    ports:
      - "${HOST_PORT_JUPYTER:-8888}:${HOST_PORT_JUPYTER:-8888}"
    entrypoint: |
      jupyter lab scripts/ --ip=0.0.0.0 --port=${HOST_PORT_JUPYTER:-8888} --allow-root --no-browser
    volumes:
      - .:/app
      - /app/tests/__pycache__/
    depends_on:
      - shell
