version: '3'
services:
  shell:
    build: .
    image: eemeter_shell_old
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    volumes:
      - .:/app
      - /app/tests/__pycache__/

  docs:
    image: eemeter_shell_old
    ports:
      - "${HOST_PORT_DOCS:-8000}:8000"
    entrypoint: make -C docs livehtml
    volumes:
      - .:/app
      - /app/tests/__pycache__/
    depends_on:
      - shell

  test:
    image: eemeter_shell_old
    entrypoint: py.test -n0
    volumes:
      - .:/app
      - /app/tests/__pycache__/
    depends_on:
      - shell

  jupyter:
    image: eemeter_shell_old
    ports:
      - "${HOST_PORT_JUPYTER:-8888}:${HOST_PORT_JUPYTER:-8888}"
    entrypoint: |
      jupyter lab scripts/ --ip=0.0.0.0 --port=${HOST_PORT_JUPYTER:-8888} --allow-root --no-browser
    volumes:
      - .:/app
      - /app/tests/__pycache__/
    depends_on:
      - shell

  eeweather:
    image: eemeter_shell_old
    entrypoint: eeweather
    volumes:
    - .:/app
    depends_on:
    - shell
